/**
 * @file aiConstants.ts
 * @description Constants for AI models, object detection classes, and smart crop weights.
 */
export const LOGO_DETECTION_CONFIG = {
    LOGO_CLASSES: [
        'logo',
        'brand',
        'emblem',
        'insignia',
        'badge',
        'crest',
        'seal',
        'trademark',
        'symbol',
        'mark',
        'signature'
    ],
    MIN_LOGO_CONFIDENCE: 0.5,
    MIN_LOGO_SIZE_RATIO: 0.005,
    MAX_LOGO_SIZE_RATIO: 0.8,
    PRIORITIZE_LOGOS: true,
    PRESERVE_WHOLE_LOGO: true,
    LOGO_PADDING_RATIO: 0.1,
    PROTECTIVE_PADDING: 0.2
} as const;

export const CATEGORY_MAPPING: Record<string, string> = {
    'person': 'person',
    'man': 'person',
    'woman': 'person',
    'boy': 'person',
    'girl': 'person',
    'child': 'person',
    'face': 'face',
    'nose': 'facial_feature',
    'eye': 'facial_feature',
    'eyes': 'facial_feature',
    'ear': 'facial_feature',
    'ears': 'facial_feature',
    'mouth': 'facial_feature',
    'lips': 'facial_feature',
    'eyebrow': 'facial_feature',
    'eyebrows': 'facial_feature',
    'forehead': 'facial_feature',
    'chin': 'facial_feature',
    'cheek': 'facial_feature',
    'jaw': 'facial_feature',
    'head': 'facial_feature',
    'hair': 'facial_feature',
    'smile': 'facial_feature',
    'hand': 'body_part',
    'hands': 'body_part',
    'finger': 'body_part',
    'fingers': 'body_part',
    'arm': 'body_part',
    'arms': 'body_part',
    'elbow': 'body_part',
    'shoulder': 'body_part',
    'shoulders': 'body_part',
    'foot': 'body_part',
    'feet': 'body_part',
    'leg': 'body_part',
    'legs': 'body_part',
    'knee': 'body_part',
    'chest': 'body_part',
    'back': 'body_part',
    'waist': 'body_part',
    'hip': 'body_part',
    'hips': 'body_part',
    'neck': 'body_part',
    'throat': 'body_part',
    'bear': 'animal',
    'dog': 'animal',
    'cat': 'animal',
    'bird': 'animal',
    'horse': 'animal',
    'sheep': 'animal',
    'cow': 'animal',
    'elephant': 'animal',
    'zebra': 'animal',
    'giraffe': 'animal',
    'lion': 'animal',
    'tiger': 'animal',
    'monkey': 'animal',
    'panda': 'animal',
    'kangaroo': 'animal',
    'wolf': 'animal',
    'fox': 'animal',
    'rabbit': 'animal',
    'mouse': 'animal',
    'rat': 'animal',
    'squirrel': 'animal',
    'deer': 'animal',
    'moose': 'animal',
    'rhinoceros': 'animal',
    'hippopotamus': 'animal',
    'camel': 'animal',
    'gorilla': 'animal',
    'chimpanzee': 'animal',
    'koala': 'animal',
    'sloth': 'animal',
    'otter': 'animal',
    'whale': 'animal',
    'dolphin': 'animal',
    'shark': 'animal',
    'turtle': 'animal',
    'snake': 'animal',
    'lizard': 'animal',
    'frog': 'animal',
    'toad': 'animal',
    'crocodile': 'animal',
    'alligator': 'animal',
    'dinosaur': 'animal',
    'dragon': 'animal',
    'eagle': 'bird',
    'hawk': 'bird',
    'owl': 'bird',
    'parrot': 'bird',
    'penguin': 'bird',
    'flamingo': 'bird',
    'peacock': 'bird',
    'swan': 'bird',
    'duck': 'bird',
    'goose': 'bird',
    'chicken': 'bird',
    'rooster': 'bird',
    'turkey': 'bird',
    'pigeon': 'bird',
    'sparrow': 'bird',
    'raven': 'bird',
    'crow': 'bird',
    'woodpecker': 'bird',
    'hummingbird': 'bird',
    'butterfly': 'insect',
    'bee': 'insect',
    'wasp': 'insect',
    'ant': 'insect',
    'spider': 'insect',
    'ladybug': 'insect',
    'beetle': 'insect',
    'dragonfly': 'insect',
    'mosquito': 'insect',
    'fly': 'insect',
    'grasshopper': 'insect',
    'cricket': 'insect',
    'cockroach': 'insect',
    'scorpion': 'insect',
    'centipede': 'insect',
    'millipede': 'insect',
    'worm': 'insect',
    'caterpillar': 'insect',
    'car': 'vehicle',
    'truck': 'vehicle',
    'bus': 'vehicle',
    'motorcycle': 'vehicle',
    'bicycle': 'vehicle',
    'train': 'vehicle',
    'airplane': 'vehicle',
    'boat': 'vehicle',
    'ship': 'vehicle',
    'yacht': 'vehicle',
    'helicopter': 'vehicle',
    'rocket': 'vehicle',
    'spaceship': 'vehicle',
    'submarine': 'vehicle',
    'tank': 'vehicle',
    'bulldozer': 'vehicle',
    'excavator': 'vehicle',
    'tractor': 'vehicle',
    'ambulance': 'vehicle',
    'fire truck': 'vehicle',
    'police car': 'vehicle',
    'taxi': 'vehicle',
    'scooter': 'vehicle',
    'skateboard': 'vehicle',
    'rollerblades': 'vehicle',
    'snowboard': 'vehicle',
    'ski': 'vehicle',
    'skis': 'vehicle',
    'frisbee': 'sports',
    'kite': 'sports',
    'surfboard': 'sports',
    'ski pole': 'sports',
    'chair': 'furniture',
    'sofa': 'furniture',
    'couch': 'furniture',
    'bed': 'furniture',
    'table': 'furniture',
    'desk': 'furniture',
    'cabinet': 'furniture',
    'wardrobe': 'furniture',
    'bookshelf': 'furniture',
    'dresser': 'furniture',
    'nightstand': 'furniture',
    'ottoman': 'furniture',
    'bench': 'furniture',
    'stool': 'furniture',
    'dining table': 'furniture',
    'pizza': 'food',
    'hot dog': 'food',
    'sandwich': 'food',
    'hamburger': 'food',
    'burger': 'food',
    'apple': 'food',
    'orange': 'food',
    'banana': 'food',
    'broccoli': 'food',
    'carrot': 'food',
    'cake': 'food',
    'cookie': 'food',
    'donut': 'food',
    'ice cream': 'food',
    'french fries': 'food',
    'fried chicken': 'food',
    'steak': 'food',
    'fish': 'food',
    'sushi': 'food',
    'ramen': 'food',
    'pasta': 'food',
    'rice': 'food',
    'bread': 'food',
    'cheese': 'food',
    'egg': 'food',
    'milk': 'food',
    'coffee': 'food',
    'tea': 'food',
    'wine': 'food',
    'beer': 'food',
    'cocktail': 'food',
    'soda': 'food',
    'water': 'food',
    'juice': 'food',
    'cell phone': 'electronics',
    'laptop': 'electronics',
    'tv': 'electronics',
    'remote': 'electronics',
    'keyboard': 'electronics',
    'monitor': 'electronics',
    'printer': 'electronics',
    'scanner': 'electronics',
    'camera': 'electronics',
    'speaker': 'electronics',
    'headphones': 'electronics',
    'microphone': 'electronics',
    'tablet': 'electronics',
    'smartwatch': 'electronics',
    'router': 'electronics',
    'game console': 'electronics',
    'controller': 'electronics',
    'backpack': 'bag',
    'handbag': 'bag',
    'suitcase': 'bag',
    'briefcase': 'bag',
    'wallet': 'accessory',
    'purse': 'accessory',
    'umbrella': 'accessory',
    'tie': 'accessory',
    'belt': 'accessory',
    'watch': 'accessory',
    'bracelet': 'accessory',
    'necklace': 'accessory',
    'ring': 'accessory',
    'earring': 'accessory',
    'glasses': 'accessory',
    'sunglasses': 'accessory',
    'hat': 'accessory',
    'cap': 'accessory',
    'scarf': 'accessory',
    'glove': 'accessory',
    'mitten': 'accessory',
    'sports ball': 'sports',
    'baseball': 'sports',
    'baseball bat': 'sports',
    'baseball glove': 'sports',
    'basketball': 'sports',
    'football': 'sports',
    'soccer ball': 'sports',
    'tennis ball': 'sports',
    'tennis racket': 'sports',
    'golf club': 'sports',
    'golf ball': 'sports',
    'hockey stick': 'sports',
    'hockey puck': 'sports',
    'helmet': 'sports',
    'dumbbell': 'sports',
    'barbell': 'sports',
    'yoga mat': 'sports',
    'jump rope': 'sports',
    'bottle': 'kitchen',
    'wine glass': 'kitchen',
    'cup': 'kitchen',
    'mug': 'kitchen',
    'glass': 'kitchen',
    'fork': 'kitchen',
    'knife': 'kitchen',
    'spoon': 'kitchen',
    'plate': 'kitchen',
    'bowl': 'kitchen',
    'pot': 'kitchen',
    'pan': 'kitchen',
    'microwave': 'kitchen',
    'oven': 'kitchen',
    'toaster': 'kitchen',
    'blender': 'kitchen',
    'mixer': 'kitchen',
    'refrigerator': 'kitchen',
    'freezer': 'kitchen',
    'dishwasher': 'kitchen',
    'sink': 'kitchen',
    'faucet': 'kitchen',
    'tree': 'nature',
    'flower': 'nature',
    'plant': 'nature',
    'grass': 'nature',
    'leaf': 'nature',
    'mountain': 'nature',
    'river': 'nature',
    'lake': 'nature',
    'ocean': 'nature',
    'sea': 'nature',
    'beach': 'nature',
    'sand': 'nature',
    'rock': 'nature',
    'stone': 'nature',
    'cloud': 'nature',
    'sky': 'nature',
    'sun': 'nature',
    'moon': 'nature',
    'star': 'nature',
    'rainbow': 'nature',
    'snow': 'nature',
    'ice': 'nature',
    'fire': 'nature',
    'potted plant': 'nature',
    'house': 'building',
    'building': 'building',
    'skyscraper': 'building',
    'tower': 'building',
    'bridge': 'building',
    'castle': 'building',
    'church': 'building',
    'temple': 'building',
    'mosque': 'building',
    'synagogue': 'building',
    'statue': 'building',
    'fountain': 'building',
    'monument': 'building',
    'shirt': 'clothing',
    't-shirt': 'clothing',
    'blouse': 'clothing',
    'dress': 'clothing',
    'skirt': 'clothing',
    'pants': 'clothing',
    'jeans': 'clothing',
    'shorts': 'clothing',
    'jacket': 'clothing',
    'coat': 'clothing',
    'sweater': 'clothing',
    'hoodie': 'clothing',
    'sweatshirt': 'clothing',
    'underwear': 'clothing',
    'socks': 'clothing',
    'shoes': 'clothing',
    'sneakers': 'clothing',
    'boots': 'clothing',
    'sandals': 'clothing',
    'slippers': 'clothing',
    'logo': 'logo',
    'sign': 'logo',
    'symbol': 'logo',
    'emblem': 'logo',
    'badge': 'logo',
    'mark': 'logo',
    'crest': 'logo',
    'insignia': 'logo',
    'seal': 'logo',
    'stamp': 'logo',
    'brand': 'logo',
    'trademark': 'logo',
    'monogram': 'logo',
    'watermark': 'logo',
    'signature': 'logo',
    'mascot': 'logo',
    'default': 'default'
};

export const CATEGORY_WEIGHTS: Record<string, number> = {
    'face': 10.0,
    'person': 6.0,
    'animal': 6.0,
    'food': 4.5,
    'facial_feature': 4.0,
    'body_part': 3.0,
    'logo': 3.0,
    'bird': 1.5,
    'insect': 1.3,
    'vehicle': 1.2,
    'bag': 1.1,
    'accessory': 1.0,
    'clothing': 1.0,
    'furniture': 0.8,
    'sports': 0.8,
    'nature': 0.7,
    'building': 0.6,
    'electronics': 0.1,
    'kitchen': 0.1,
    'default': 1.0
};

export const IGNORED_OBJECTS = [
    'remote', 'keyboard', 'mouse', 'cup', 'bowl', 'smart phone',
    'fork', 'knife', 'spoon', 'cell phone', 'mobile phone', 'cellphone', 'smartphone', 'handphone', 'phone',
    'pen', 'pencil', 'paper', 'notebook', 'clock', 'watch', 'calculator',
    'charger', 'cable', 'plug', 'socket', 'outlet', 'switch', 'button',
    'doorknob', 'handle', 'hinge', 'screw', 'nail', 'bolt', 'nut',
    'dust', 'dirt', 'stain', 'spot', 'mark', 'scratch', 'crack',
    'shadow', 'reflection', 'glare', 'blur', 'noise', 'artifact'
];

export const AI_MODEL_WEIGHTS = {
    SIZE_WEIGHT: 0.4,
    CONFIDENCE_WEIGHT: 0.4,
    CENTRALITY_WEIGHT: 0.2,
    PERSON_CLASS_WEIGHT: 1.5,
    FACE_CLASS_WEIGHT: 1.3,
    ANIMAL_CLASS_WEIGHT: 1.2,
    DEFAULT_CLASS_WEIGHT: 1.0
} as const;

export const AI_SETTINGS = {
    MIN_CONFIDENCE: 0.3,
    MIN_SUBJECT_SCORE: 0.2,
    FACE_DETECTION_ENABLED: true,
    OBJECT_DETECTION_ENABLED: true,
    DEFAULT_CROP_STRATEGY: 'balanced',
    MAX_OBJECTS: 10,
    MODEL_TYPE: 'yolov8n',
    TENSORFLOW_VERSION: '4.22.0',
    COCO_SSD_VERSION: '2.2.3',
    WEBGPU_BACKEND_VERSION: '4.22.0',
    LOCAL_MODEL_PATH: '/models/',
    LOCAL_LIB_PATH: '/lib/'
} as const;

export const SMART_CROP_CONFIG = {
    DEFAULT_STRATEGY: 'ai_priority',
    MIN_SUBJECT_SIZE_RATIO: 0.05,
    MAX_SUBJECT_SIZE_RATIO: 0.95,
    PADDING_RATIO: 0.1,
    FALLBACK_TO_CENTER: true,
    USE_FACIAL_FEATURES: true,
    ENABLE_EDGE_DETECTION: true
} as const;
