// @ts-ignore
import JSZip from 'jszip';
import {
    FAVICON_SIZES,
    FAVICON_SIZES_BASIC,
    FAVICON_ICO_SIZES,
    FAVICON_PREVIEW_SIZE,
    APP_TEMPLATE_CONFIG,
    DEFAULT_FAVICON_SITE_NAME,
    DEFAULT_FAVICON_THEME_COLOR,
    DEFAULT_FAVICON_BACKGROUND_COLOR
} from '../configs/templateConfigs';

/**
 * Generates a complete favicon set from an image
 * @async
 * @param {File} imageFile - Source image file
 * @param {string} siteName - Name of the website
 * @param {string} themeColor - Theme color for manifest
 * @param {string} backgroundColor - Background color for manifest
 * @param {string} mode - Generation mode ('complete' or 'basic')
 * @returns {Promise<Blob>} ZIP file containing the favicon set
 */
export const generateFaviconSet = async (
    imageFile: File,
    siteName: string = DEFAULT_FAVICON_SITE_NAME,
    themeColor: string = DEFAULT_FAVICON_THEME_COLOR,
    backgroundColor: string = DEFAULT_FAVICON_BACKGROUND_COLOR,
    mode: string = 'complete'
): Promise<Blob> => {
    const zip = new JSZip();
    const targetSizes = mode === 'basic' ? FAVICON_SIZES_BASIC : FAVICON_SIZES;

    const manifest = {
        "name": siteName,
        "short_name": siteName,
        "description": `${siteName} - Favicon set generated by LemGend`,
        "icons": targetSizes
            .filter(size =>
                size.name.includes('favicon') ||
                size.name.includes('android-chrome') ||
                size.name.includes('apple-touch-icon')
            )
            .map(size => ({
                "src": `/${size.name}.png`,
                "sizes": `${size.width}x${size.height}`,
                "type": "image/png",
                "purpose": size.name.includes('apple-touch-icon') ? "maskable any" : "any"
            })),
        "theme_color": themeColor,
        "background_color": backgroundColor,
        "display": "standalone",
        "orientation": "any",
        "scope": "/",
        "start_url": "/",
        "lang": "en"
    };

    zip.file("site.webmanifest", JSON.stringify(manifest, null, 2));

    const htmlSnippet = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${siteName}</title>

    <link rel="icon" type="image/x-icon" href="/favicon.ico">
    ${targetSizes
            .filter(size => size.name.includes('favicon') && !size.name.includes('64x64'))
            .map(size => `<link rel="icon" type="image/png" sizes="${size.width}x${size.height}" href="/${size.name}.png">`)
            .join('\n    ')}

    ${targetSizes
            .filter(size => size.name.includes('apple-touch-icon'))
            .map(size => `<link rel="apple-touch-icon" sizes="${size.width}x${size.height}" href="/${size.name}.png">`)
            .join('\n    ')}

    ${targetSizes
            .filter(size => size.name.includes('android-chrome'))
            .map(size => `<link rel="icon" type="image/png" sizes="${size.width}x${size.height}" href="/${size.name}.png">`)
            .join('\n    ')}

    <meta name="msapplication-TileColor" content="${themeColor}">
    ${targetSizes
            .filter(size => size.name.includes('mstile'))
            .map(size => `<meta name="msapplication-TileImage" content="/${size.name}.png">`)
            .join('\n    ')}

    <link rel="manifest" href="/site.webmanifest">

    <meta name="theme-color" content="${themeColor}">

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="msapplication-config" content="/browserconfig.xml">
</head>
<body>
</body>
</html>`;

    zip.file("favicon-html-snippet.html", htmlSnippet);

    const browserConfig = `<?xml version="1.0" encoding="utf-8"?>
<browserconfig>
    <msapplication>
        <tile>
            ${targetSizes
            .filter(size => size.name.includes('mstile'))
            .map(size => `<${size.name.includes('310x150') ? 'wide' : 'square'}${size.width}x${size.height}logo src="/${size.name}.png"/>`)
            .join('\n            ')}
            <TileColor>${themeColor}</TileColor>
        </tile>
    </msapplication>
</browserconfig>`;

    zip.file("browserconfig.xml", browserConfig);

    const readme = `Favicon Set - ${siteName}
=====================

This ZIP file contains a ${mode} favicon set for your website, generated by LemGend.

Files Included

Core Favicons
${targetSizes.map(size => `- ${size.name}.png - ${size.width}x${size.height} pixels`).join('\n')}
- favicon.ico - ICO format with multiple sizes (${FAVICON_ICO_SIZES.join(', ')})

Configuration Files
- site.webmanifest - Web App Manifest for PWA support
- browserconfig.xml - Windows Metro/Modern UI configuration
- favicon-html-snippet.html - Complete HTML snippet for easy implementation

Documentation
- readme.txt - This file

Quick Start

Method 1: Complete Implementation
1. Extract all files to your website's root directory
2. Copy the entire head section from favicon-html-snippet.html
3. Paste it into your website's head section
4. Test on different devices and browsers

Method 2: Minimal Implementation
Add just these lines to your head:

<!-- Favicon & App Icons -->
<link rel="icon" type="image/x-icon" href="/favicon.ico">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="192x192" href="/android-chrome-192x192.png">
${mode === 'basic'
            ? `<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">`
            : `<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">`}
<link rel="manifest" href="/site.webmanifest">
<meta name="theme-color" content="${themeColor}">

Device & Browser Support

Apple Devices
- iPhone/iPad: Uses 180x180 icon
- Retina Displays: Uses 180x180 for @2x, 76x76 for @1x
- Apple Touch Bar: Uses 16x16, 32x32

Android Devices
- Chrome for Android: Uses 192x192 and 512x512
- Android Home Screen: Uses 48x48, 96x96
- Android TV: Uses 128x128

Windows Devices
- Windows 10/11: Uses browserconfig.xml for live tiles
- Microsoft Edge: Uses manifest and standard icons
- Internet Explorer: Uses ICO file and 16x16/32x32 PNGs

Desktop Browsers
- Chrome/Firefox/Safari: Use standard favicon.ico and PNGs
- Opera: Uses 32x32 and 64x64
- Bookmarks: Use 16x16 for bookmark icons

File Specifications

favicon.ico
Contains multiple sizes in one file:
${FAVICON_ICO_SIZES.map(size => `- ${size}x${size} (${getIconPurpose(size)})`).join('\n')}

PNG Files
All PNGs are:
- Optimized for web use
- Transparent background (where applicable)
- Properly anti-aliased for small sizes
- High-quality compression

site.webmanifest
Includes:
- App name: "${siteName}"
- Theme color: ${themeColor}
- Background color: ${backgroundColor}
- Display mode: standalone
- Icon specifications for all sizes

Technical Notes

File Placement
Place all files in your website's root directory (same level as index.html).

File Paths
All paths in the HTML snippet are root-relative (/filename.png).
If your site uses a subdirectory, update the paths accordingly.

Cache Control
For production use, set appropriate cache headers:

# NGINX
location ~* \\.(ico|png|xml|webmanifest)$ {
    expires 1y;
    add_header Cache-Control "public, immutable";
}

# Apache
<FilesMatch "\\.(ico|png|xml|webmanifest)$">
    Header set Cache-Control "max-age=31536000, public, immutable"
</FilesMatch>

Content Security
The favicon files are safe and contain no executable code.
They're standard image files with proper MIME types.

Testing Checklist

- Favicon displays in browser tab
- Apple touch icon works on iOS devices
- Android Chrome shows correct icon
- Windows taskbar shows icon
- Site manifest loads correctly
- No console errors related to favicons
- All image files are accessible (404 check)
- Print screen shows favicon in print preview

Troubleshooting

Favicon Not Showing
1. Clear browser cache: Ctrl+F5 or Cmd+Shift+R
2. Check file permissions
3. Verify file paths are correct
4. Check for syntax errors in HTML

Wrong Icon Displaying
1. Delete old favicon files from server
2. Clear CDN cache if using one
3. Wait for DNS propagation
4. Check for conflicting favicon declarations

Performance Issues
- All images are optimized, but you can further compress if needed
- Consider using HTTP/2 for parallel loading
- Use a CDN for global distribution

License & Usage
These favicons are generated for use with "${siteName}".
You're free to use them in your project.
Generated by LemGend Favicon Generator.

---
For more help, visit: https://lemgend.com
Generated on: ${new Date().toLocaleDateString()}`;

    zip.file("readme.txt", readme);

    const img = new Image();
    const objectUrl = URL.createObjectURL(imageFile);

    await new Promise((resolve, reject) => {
        img.onload = resolve;
        img.onerror = reject;
        img.src = objectUrl;
    });

    for (const size of targetSizes) {
        const canvas = document.createElement('canvas'); // in worker or main thread? Assuming main thread for now since strict DOM access
        const ctx = canvas.getContext('2d');
        if (!ctx) continue;

        canvas.width = size.width;
        canvas.height = size.height;

        if (size.width <= 48 || size.name.includes('favicon')) {
            ctx.fillStyle = backgroundColor;
            ctx.fillRect(0, 0, size.width, size.height);
        } else {
            ctx.clearRect(0, 0, size.width, size.height);
        }

        if (size.width <= 48) {
            const padding = size.width <= 16 ? 1 : 2;
            const scale = Math.min(
                (size.width - padding * 2) / img.width,
                (size.height - padding * 2) / img.height
            );
            const scaledWidth = img.width * scale;
            const scaledHeight = img.height * scale;
            const x = (size.width - scaledWidth) / 2;
            const y = (size.height - scaledHeight) / 2;

            ctx.imageSmoothingEnabled = true;
            ctx.imageSmoothingQuality = 'high';
            ctx.drawImage(img, x, y, scaledWidth, scaledHeight);
        } else {
            ctx.imageSmoothingEnabled = true;
            ctx.imageSmoothingQuality = 'high';

            const scale = Math.min(size.width / img.width, size.height / img.height);
            const scaledWidth = img.width * scale;
            const scaledHeight = img.height * scale;
            const x = (size.width - scaledWidth) / 2;
            const y = (size.height - scaledHeight) / 2;

            ctx.drawImage(img, x, y, scaledWidth, scaledHeight);
        }

        const blob = await new Promise(resolve => {
            canvas.toBlob(resolve, 'image/png', 0.9);
        });

        if (blob) {
            zip.file(`${size.name}.png`, blob as Blob);
        }
    }

    const icoCanvases = FAVICON_ICO_SIZES.map(size => {
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d');
        if (!ctx) return null;
        canvas.width = size;
        canvas.height = size;

        ctx.fillStyle = backgroundColor;
        ctx.fillRect(0, 0, size, size);

        const padding = size <= 16 ? 1 : 2;
        const scale = Math.min(
            (size - padding * 2) / img.width,
            (size - padding * 2) / img.height
        );
        const scaledWidth = img.width * scale;
        const scaledHeight = img.height * scale;
        const x = (size - scaledWidth) / 2;
        const y = (size - scaledHeight) / 2;

        ctx.imageSmoothingEnabled = true;
        ctx.imageSmoothingQuality = size <= 32 ? 'low' : 'medium';
        ctx.drawImage(img, x, y, scaledWidth, scaledHeight);

        return canvas;
    }).filter(c => c !== null) as HTMLCanvasElement[];

    const icoCanvas = icoCanvases.find(c => c.width === 32) || icoCanvases[0];
    if (icoCanvas) {
        const icoBlob = await new Promise(resolve => {
            icoCanvas.toBlob(resolve, 'image/x-icon');
        });
        if (icoBlob) {
            zip.file("favicon.ico", icoBlob as Blob);
        }
    }

    URL.revokeObjectURL(objectUrl);

    return await zip.generateAsync({
        type: 'blob',
        compression: 'DEFLATE',
        compressionOptions: { level: 6 }
    });
};

/**
 * Helper function to get icon purpose description
 * @param {number} size - Icon size
 * @returns {string} Purpose description
 */
function getIconPurpose(size: number): string {
    const purposes: Record<number, string> = {
        16: 'browser tabs, bookmarks',
        32: 'taskbars, Windows',
        48: 'desktop shortcuts',
        64: 'high-DPI displays'
    };
    return purposes[size] || 'general use';
}

/**
 * Generates a preview of the favicon at FAVICON_PREVIEW_SIZE
 * @async
 * @param {File} imageFile - Source image file
 * @param {string} backgroundColor - Background color
 * @returns {Promise<Blob>} Preview image blob
 */
export const generateFaviconPreview = async (imageFile: File, backgroundColor: string = DEFAULT_FAVICON_BACKGROUND_COLOR): Promise<Blob> => {
    const img = new Image();
    const objectUrl = URL.createObjectURL(imageFile);

    await new Promise((resolve, reject) => {
        img.onload = resolve;
        img.onerror = reject;
        img.src = objectUrl;
    });

    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    if (!ctx) throw new Error("No context");

    canvas.width = FAVICON_PREVIEW_SIZE;
    canvas.height = FAVICON_PREVIEW_SIZE;

    ctx.fillStyle = backgroundColor;
    ctx.fillRect(0, 0, FAVICON_PREVIEW_SIZE, FAVICON_PREVIEW_SIZE);

    const scale = Math.min(
        FAVICON_PREVIEW_SIZE / img.width,
        FAVICON_PREVIEW_SIZE / img.height
    ) * 0.85;
    const scaledWidth = img.width * scale;
    const scaledHeight = img.height * scale;
    const x = (FAVICON_PREVIEW_SIZE - scaledWidth) / 2;
    const y = (FAVICON_PREVIEW_SIZE - scaledHeight) / 2;

    ctx.imageSmoothingEnabled = true;
    ctx.imageSmoothingQuality = 'high';
    ctx.drawImage(img, x, y, scaledWidth, scaledHeight);

    URL.revokeObjectURL(objectUrl);

    return new Promise((resolve, reject) => {
        canvas.toBlob((blob) => {
            if (blob) {
                resolve(blob);
            } else {
                reject(new Error("Failed to create blob"));
            }
        }, 'image/png', 0.9);
    });
};

/**
 * Gets the count of files that will be generated
 * @returns {number} Total file count in favicon set
 */
export const getFaviconFileCount = (): number => {
    return FAVICON_SIZES.length + 5;
};

/**
 * Gets the folder name for favicon exports
 * @returns {string} Folder name
 */
export const getFaviconFolderName = (): string => {
    return APP_TEMPLATE_CONFIG.FAVICON.FOLDER_NAME;
};
